spring:
  application:
    name: JackpotService
  datasource:
    url: jdbc:h2:mem:jackpotdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: true

jackpot:
  defaults:
    topic: jackpot-bets
    jackpots:
      - id: JACKPOT-1
        initialPoolAmount: 1000
        contributionType: FIXED
        fixedContributionPercentage: 5
        rewardType: FIXED
        fixedRewardChancePercentage: 1
      - id: JACKPOT-2
        initialPoolAmount: 120
        contributionType: FIXED
        fixedContributionPercentage: 100
        rewardType: VARIABLE
        variableRewardBaseChancePercentage: 0
        variableRewardIncreaseRatePercentage: 0
        variableRewardIncreaseStep: 1
        variableRewardGuaranteedPoolLimit: 150

logging:
  level:
    com.sporty.jackpotservice: INFO
